model:
  cfg_path: ./config/sample_sr3_128_Liver.json
  pretrained_path: ./Pretrained/Liver_128.pth
data:
  root: ./test_data/Liver
  input_folder: low
  cond_folder: None
  output_folder: lr_dn
  target_folder: full
  res: 128 # the input images will be first resized to (res, res) befor denoising
  len: -1 # -1 for testing all images in the input folder
diffusion:
  ddim: True
  ddim_eta: 1.0
dn:
  # mode==0: ConsLam
  # mode==1: AdaLamI 
  # mode==2: AdaLamII
  # mode==3: AdaLamI&II
  mode: 0
  lam0: 0.002 # ConsLam: $\lambda_t=\lambda_0\cdot\sqrt{\bar{\alpha}_t}$
  a: 0 
  b: 0 # AdaLamI: $\lambda_0^{ada} = a \cdot std(\widehat{n}) + b$
  c: 0 # AdaLamII: $\Lambda_0^{ada} = c \cdot \widehat{n}$
  resume: 3
  mean_num: 10 # multiple denoising and take average, reduce mean_num if CUDA_OUT_OF_MEMORY
  bs: 10 # batch size
